//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision_X.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.ShapingWebServiceSoap")]
    public interface ShapingWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name type from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/shaper", ReplyAction="*")]
        Vision_X.ServiceReference.shaperResponse shaper(Vision_X.ServiceReference.shaperRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/shaper", ReplyAction="*")]
        System.Threading.Tasks.Task<Vision_X.ServiceReference.shaperResponse> shaperAsync(Vision_X.ServiceReference.shaperRequest request);
        
        // CODEGEN: Generating message contract since element name type from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/rectangle", ReplyAction="*")]
        Vision_X.ServiceReference.rectangleResponse rectangle(Vision_X.ServiceReference.rectangleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/rectangle", ReplyAction="*")]
        System.Threading.Tasks.Task<Vision_X.ServiceReference.rectangleResponse> rectangleAsync(Vision_X.ServiceReference.rectangleRequest request);
        
        // CODEGEN: Generating message contract since element name type from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/triangle", ReplyAction="*")]
        Vision_X.ServiceReference.triangleResponse triangle(Vision_X.ServiceReference.triangleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/triangle", ReplyAction="*")]
        System.Threading.Tasks.Task<Vision_X.ServiceReference.triangleResponse> triangleAsync(Vision_X.ServiceReference.triangleRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class shaperRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="shaper", Namespace="http://tempuri.org/", Order=0)]
        public Vision_X.ServiceReference.shaperRequestBody Body;
        
        public shaperRequest() {
        }
        
        public shaperRequest(Vision_X.ServiceReference.shaperRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class shaperRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string type;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int n;
        
        public shaperRequestBody() {
        }
        
        public shaperRequestBody(string type, int n) {
            this.type = type;
            this.n = n;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class shaperResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="shaperResponse", Namespace="http://tempuri.org/", Order=0)]
        public Vision_X.ServiceReference.shaperResponseBody Body;
        
        public shaperResponse() {
        }
        
        public shaperResponse(Vision_X.ServiceReference.shaperResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class shaperResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string shaperResult;
        
        public shaperResponseBody() {
        }
        
        public shaperResponseBody(string shaperResult) {
            this.shaperResult = shaperResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class rectangleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="rectangle", Namespace="http://tempuri.org/", Order=0)]
        public Vision_X.ServiceReference.rectangleRequestBody Body;
        
        public rectangleRequest() {
        }
        
        public rectangleRequest(Vision_X.ServiceReference.rectangleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class rectangleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string type;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int n;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int l;
        
        public rectangleRequestBody() {
        }
        
        public rectangleRequestBody(string type, int n, int l) {
            this.type = type;
            this.n = n;
            this.l = l;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class rectangleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="rectangleResponse", Namespace="http://tempuri.org/", Order=0)]
        public Vision_X.ServiceReference.rectangleResponseBody Body;
        
        public rectangleResponse() {
        }
        
        public rectangleResponse(Vision_X.ServiceReference.rectangleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class rectangleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rectangleResult;
        
        public rectangleResponseBody() {
        }
        
        public rectangleResponseBody(string rectangleResult) {
            this.rectangleResult = rectangleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class triangleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="triangle", Namespace="http://tempuri.org/", Order=0)]
        public Vision_X.ServiceReference.triangleRequestBody Body;
        
        public triangleRequest() {
        }
        
        public triangleRequest(Vision_X.ServiceReference.triangleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class triangleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string type;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int n;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int l;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int k;
        
        public triangleRequestBody() {
        }
        
        public triangleRequestBody(string type, int n, int l, int k) {
            this.type = type;
            this.n = n;
            this.l = l;
            this.k = k;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class triangleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="triangleResponse", Namespace="http://tempuri.org/", Order=0)]
        public Vision_X.ServiceReference.triangleResponseBody Body;
        
        public triangleResponse() {
        }
        
        public triangleResponse(Vision_X.ServiceReference.triangleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class triangleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string triangleResult;
        
        public triangleResponseBody() {
        }
        
        public triangleResponseBody(string triangleResult) {
            this.triangleResult = triangleResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ShapingWebServiceSoapChannel : Vision_X.ServiceReference.ShapingWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShapingWebServiceSoapClient : System.ServiceModel.ClientBase<Vision_X.ServiceReference.ShapingWebServiceSoap>, Vision_X.ServiceReference.ShapingWebServiceSoap {
        
        public ShapingWebServiceSoapClient() {
        }
        
        public ShapingWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShapingWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShapingWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShapingWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vision_X.ServiceReference.shaperResponse Vision_X.ServiceReference.ShapingWebServiceSoap.shaper(Vision_X.ServiceReference.shaperRequest request) {
            return base.Channel.shaper(request);
        }
        
        public string shaper(string type, int n) {
            Vision_X.ServiceReference.shaperRequest inValue = new Vision_X.ServiceReference.shaperRequest();
            inValue.Body = new Vision_X.ServiceReference.shaperRequestBody();
            inValue.Body.type = type;
            inValue.Body.n = n;
            Vision_X.ServiceReference.shaperResponse retVal = ((Vision_X.ServiceReference.ShapingWebServiceSoap)(this)).shaper(inValue);
            return retVal.Body.shaperResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vision_X.ServiceReference.shaperResponse> Vision_X.ServiceReference.ShapingWebServiceSoap.shaperAsync(Vision_X.ServiceReference.shaperRequest request) {
            return base.Channel.shaperAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vision_X.ServiceReference.shaperResponse> shaperAsync(string type, int n) {
            Vision_X.ServiceReference.shaperRequest inValue = new Vision_X.ServiceReference.shaperRequest();
            inValue.Body = new Vision_X.ServiceReference.shaperRequestBody();
            inValue.Body.type = type;
            inValue.Body.n = n;
            return ((Vision_X.ServiceReference.ShapingWebServiceSoap)(this)).shaperAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vision_X.ServiceReference.rectangleResponse Vision_X.ServiceReference.ShapingWebServiceSoap.rectangle(Vision_X.ServiceReference.rectangleRequest request) {
            return base.Channel.rectangle(request);
        }
        
        public string rectangle(string type, int n, int l) {
            Vision_X.ServiceReference.rectangleRequest inValue = new Vision_X.ServiceReference.rectangleRequest();
            inValue.Body = new Vision_X.ServiceReference.rectangleRequestBody();
            inValue.Body.type = type;
            inValue.Body.n = n;
            inValue.Body.l = l;
            Vision_X.ServiceReference.rectangleResponse retVal = ((Vision_X.ServiceReference.ShapingWebServiceSoap)(this)).rectangle(inValue);
            return retVal.Body.rectangleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vision_X.ServiceReference.rectangleResponse> Vision_X.ServiceReference.ShapingWebServiceSoap.rectangleAsync(Vision_X.ServiceReference.rectangleRequest request) {
            return base.Channel.rectangleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vision_X.ServiceReference.rectangleResponse> rectangleAsync(string type, int n, int l) {
            Vision_X.ServiceReference.rectangleRequest inValue = new Vision_X.ServiceReference.rectangleRequest();
            inValue.Body = new Vision_X.ServiceReference.rectangleRequestBody();
            inValue.Body.type = type;
            inValue.Body.n = n;
            inValue.Body.l = l;
            return ((Vision_X.ServiceReference.ShapingWebServiceSoap)(this)).rectangleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vision_X.ServiceReference.triangleResponse Vision_X.ServiceReference.ShapingWebServiceSoap.triangle(Vision_X.ServiceReference.triangleRequest request) {
            return base.Channel.triangle(request);
        }
        
        public string triangle(string type, int n, int l, int k) {
            Vision_X.ServiceReference.triangleRequest inValue = new Vision_X.ServiceReference.triangleRequest();
            inValue.Body = new Vision_X.ServiceReference.triangleRequestBody();
            inValue.Body.type = type;
            inValue.Body.n = n;
            inValue.Body.l = l;
            inValue.Body.k = k;
            Vision_X.ServiceReference.triangleResponse retVal = ((Vision_X.ServiceReference.ShapingWebServiceSoap)(this)).triangle(inValue);
            return retVal.Body.triangleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vision_X.ServiceReference.triangleResponse> Vision_X.ServiceReference.ShapingWebServiceSoap.triangleAsync(Vision_X.ServiceReference.triangleRequest request) {
            return base.Channel.triangleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vision_X.ServiceReference.triangleResponse> triangleAsync(string type, int n, int l, int k) {
            Vision_X.ServiceReference.triangleRequest inValue = new Vision_X.ServiceReference.triangleRequest();
            inValue.Body = new Vision_X.ServiceReference.triangleRequestBody();
            inValue.Body.type = type;
            inValue.Body.n = n;
            inValue.Body.l = l;
            inValue.Body.k = k;
            return ((Vision_X.ServiceReference.ShapingWebServiceSoap)(this)).triangleAsync(inValue);
        }
    }
}
